### ISSUE TITLE
Limitation: does not support native modules 

### ISSUE THREAD

**Issue by judfs** [simon-ritchie/stubdoc#4]
I was hoping to make docs for [lcm](https://github.com/lcm-proj/lcm)'s python bindings.
```
stubgen  -p lcm
stubdoc -m lcm/__init__.py -s out/lcm/__init__.pyi
stubdoc -m lcm/_lcm.so -s out/lcm/_lcm.pyi
```
The docs are successfully scraped from the python source init file and added to its stub, but the stub for the native module remains unchanged. Pydoc does display help for this native module. 

Probably a fair bit more complicated to support, but making this issue at least for documentation.

**Comment by simon-ritchie** [comment]
Hi, @judfs 
Thx for posting this issue!

I don't usually work with files with .so extensions, so it is difficult for me to develop and support it.

Is it possible to share .so extension files for development and testing?

**Comment by simon-ritchie** [comment]
I closed this issue since there has been no response.
