### ISSUE TITLE
Docstring missing for imported classes

### ISSUE THREAD

**Issue by YodaEmbedding** [simon-ritchie/stubdoc#9]
Given the following module files:

```python
# packages/package/parent.py

class Parent:
    def shared(self):
        """This should be shared by Child, too."""
```

```python
# packages/package/child.py

class Child(Parent):
    pass
```

And the following stub files:

```python
# stubs/package/child.pyi

class Child(Parent):
    def shared(self):
        ...
```

The following command does not copy over the docstring:

```bash
stubdoc --module_path=packages/package/child.py --stub_path=stubs/package/child.pyi
```

**Comment by simon-ritchie** [comment]
Hi, @YodaEmbedding 
Thanks for reporting.

Currently, This library only supports docstrings for the methods defined in that class.

In the provided sample code, if you create a stub file for 'parent.py', the docstring will be reflected there. Additionally, even in the parent class stub, if you use tools like VS Code, the docstring should be displayed when referencing the method in the child class.

If you're overriding the method in the Child class, please include the docstring there as well.
